version: '3.1'

services:
  db:
    image: mysql
    container_name: mysqldb
    network_mode: bridge
    restart: always
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-data: